sudo: false
dist: trusty
language: c++
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
install:
 - ./.ci/travis-prepare.sh
script:
 - ./.ci/travis-build.sh
env:
 - BRCORE=master BRLIBCOM=master BRPVD=master BRPVA=master BRNT=master BRPVAC=master BRQSRV=master BRPVDB=master
 - CMPLR=clang
 - USR_CXXFLAGS=-std=c++11
 - CMPLR=clang USR_CXXFLAGS=-std=c++11
 - WINE=32 TEST=NO STATIC=YES
 - WINE=32 TEST=NO STATIC=NO
 - RTEMS=4.10 TEST=NO
 - RTEMS=4.9 TEST=NO
 - BRBASE=3.16
 - BRBASE=3.15
